name = "StaTech Industry"
author = "static"
version = "1.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "facdafec9da5bd1a494747e989924234699f0c3bf311c47a4c0858ab7ceba140"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
