#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 0
	#The name of the modpack
	modpackName = "CHANGE_ME"
	#The version of the modpack
	modpackVersion = "CHANGE_ME"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false
