#.
#Disables the migration of placed copycats from old versions to new ones. Setting this to true may cause copycats to lose their textures when you upgrade this mod. Restart the game to apply changes.
disableMigration = false

#.
#Enable/disable features. Values on server override clients
[features]
	#.
	copycat_vertical_stairs = true
	copycat_byte = true
	copycat_vertical_slice = true
	copycat_wooden_pressure_plate = true
	copycat_block = true
	copycat_shaft = true
	copycat_large_cogwheel = true
	copycat_fence = true
	copycat_wall = true
	copycat_cogwheel = true
	copycat_vertical_step = true
	copycat_slope_layer = true
	copycat_light_weighted_pressure_plate = true
	copycat_stairs = true
	copycat_fence_gate = true
	copycat_slab = true
	copycat_board = true
	copycat_wooden_button = true
	copycat_trapdoor = true
	copycat_stone_pressure_plate = true
	copycat_half_panel = true
	copycat_slice = true
	copycat_beam = true
	copycat_door = true
	copycat_iron_door = true
	copycat_ghost_block = true
	copycat_fluid_pipe = true
	copycat_heavy_weighted_pressure_plate = true
	copycat_iron_trapdoor = true
	copycat_half_layer = true
	copycat_stone_button = true
	copycat_ladder = true
	copycat_layer = true
	copycat_slope = true
	copycat_vertical_slope = true

#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#All copycats with a sloped surface
	slopes = true
	#.
	#All copycats that support multiple materials in a single block
	multistates = true
	#.
	#All copycats that can be resized by putting in more of the same copycat
	stackables = true
	#.
	#All copycats that can emit a redstone signal
	redstone = true
	#.
	#All copycats with extra functions/interactions
	functional = true
	#.
	#All copycats mimicking blocks from Create
	create = true

