#General settings
[general]
	#Should this mod add some of its items (CORN!!!) as extra chest loot across Minecraft?
	genCornLootModifier = true
	#Should this mod add corn farm to plains and taiga village?
	genCornFarm = true
	#Should Novice and Apprentice Farmers trade this mod's crops? (May reduce chances of other trades appearing)
	villagersTradeCorn = true
