#Render inventory contents of an enchanting table.
#Allowed Values: NONE, FLAT, FLOATING
render_enchanting_table_contents = "FLOATING"
#Keep the vanilla book inside the enchantment screen instead of rendering a reroll button.
#The button is simply not visible, rerolling still works by clicking the book. Disabling the reroll feature itself is possible in the server config.
keep_enchantment_screen_book = false

