[leaf_settings]
	#Modifies the size of the leaves
	# Default: 4
	# Range: 1 ~ 20
	leafSize = 4
	#Modifies how long it takes for the leaves to disappear.
	#In Ticks
	#Values over 2000 are not recommend
	# Default: 200
	# Range: > 100
	leafLifespan = 200
	#Modifies the amount of leaves that are spawning.
	#Values over 10000 are not recommend
	# Default: 10
	# Range: > 0
	leafSpawnRate = 10
	#Modifies the amount of leaves are spawning from conifer trees
	#Values over 10000 are not recommend
	# Default: 2
	# Range: > 0
	coniferLeafSpawnRate = 2
	#Whether player placed blocks should also drop leaves
	dropFromPlayerPlacedBlocks = true
	#How much room below the leaves block is needed for the leaves to spawn
	# Default: 1
	# Range: 1 ~ 20
	minimumFreeSpaceBelow = 1
	#How many leaves should spawn when a leaves block is decaying
	#This is the maximum amount, but they are binomial distributed.
	#This only works in singleplayer
	# Default: 10
	# Range: 1 ~ 1000
	decayingLeaves = 10

[wind]
	#Disable wind effects
	disableWind = false
	#Windless dimensions
	#By level registry name
	windlessDimension = ["minecraft:the_nether", "minecraft:the_end"]

[snow]
	#Disable snow particles
	disableSnow = false
	#Modifies the amount of snow that is spawning.
	#Values over 10000 are not recommend
	# Default: 10
	# Range: > 0
	snowSpawnRate = 10
	#How many snow particles should spawn when a snow block is decaying
	#This is the maximum amount, but they are binomial distributed.
	#This only works in singleplayer
	# Default: 40
	# Range: 1 ~ 1000
	decayingSnow = 40

[serene_seasons]
	#Disable the seasonal modifier when serene season is installed
	disableSeasonalModifier = false
