#Should the machine sounds be enabled?
machineSoundsEnabled = true
#Assembler volume
#Range: 0.0 ~ 5.0
assemblerVolume = 1.0
#Steam Blast Furnace volume
#Range: 0.0 ~ 5.0
blastFurnaceVolume = 1.0
#Centrifuge volume
#Range: 0.0 ~ 5.0
centrifugeVolume = 1.0
#Chemical Reactor volume
#Range: 0.0 ~ 5.0
chemicalReactorVolume = 1.0
#Coke Oven volume
#Range: 0.0 ~ 5.0
cokeOvenVolume = 1.0
#Compressor volume
#Range: 0.0 ~ 5.0
compressorVolume = 1.0
#Cutting Machine volume
#Range: 0.0 ~ 5.0
cuttingMachineVolume = 1.0
#Distillation Tower volume
#Range: 0.0 ~ 5.0
distillationTowerVolume = 1.0
#Distillery volume
#Range: 0.0 ~ 5.0
distilleryVolume = 1.0
#Electric Blast Furnace volume
#Range: 0.0 ~ 5.0
electricBlastFurnaceVolume = 1.0
#Electrolyzer volume
#Range: 0.0 ~ 5.0
electrolyzerVolume = 1.0
#Fission Reactor volume
#Range: 0.0 ~ 5.0
fissionReactorVolume = 1.0
#Fusion Reactor volume
#Range: 0.0 ~ 5.0
fusionReactorVolume = 1.0
#Furnace volume
#Range: 0.0 ~ 5.0
furnaceVolume = 1.0
#Heat Exchanger volume
#Range: 0.0 ~ 5.0
heatExchangerVolume = 1.0
#Implosion Compressor value
#Range: 0.0 ~ 5.0
implosionCompressorVolume = 1.0
#Macerator volume
#Range: 0.0 ~ 5.0
maceratorVolume = 1.0
#Mixer volume
#Range: 0.0 ~ 5.0
mixerVolume = 1.0
#Oil Drilling Rig volume
#Range: 0.0 ~ 5.0
oilDrillingRigVolume = 1.0
#Packer volume
#Range: 0.0 ~ 5.0
packerVolume = 1.0
#Polarizer volume
#Range: 0.0 ~ 5.0
polarizerVolume = 1.0
#Pressurizer volume
#Range: 0.0 ~ 5.0
pressurizerVolume = 1.0
#Quarry volume
#Range: 0.0 ~ 5.0
quarryVolume = 1.0
#Unpacker volume
#Range: 0.0 ~ 5.0
unpackerVolume = 1.0
#Vacuum Freezer volume
#Range: 0.0 ~ 5.0
vacuumFreezerVolume = 1.0
#Wiremill volume
#Range: 0.0 ~ 5.0
wiremillVolume = 1.0
#Wrench volume
#Range: 0.0 ~ 5.0
wrenchVolume = 1.0
#Replicator volume
#Range: 0.0 ~ 5.0
replicatorVolume = 1.0
