blacklistedOres = []
enableNoEmiMessage = true
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = true
enableAe2Integration = true
generateOres = true
datagenOnStartup = true
loadRuntimeGeneratedResources = true
removeIndustrialistTrades = true