[formatting]
	#How the mod name should be formatted in the tooltip. Leave blank to disable.
	#Use these formatting colors:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	#With these formatting options:
	#obfuscated, bold, strikethrough, underline, italic
	modNameFormat = "blue italic"
