#General settings
[general]

	#Settings for the wands
	[general.wandsettings]

		[general.wandsettings.general]
			#Set this to false if you don't want the durability bar for wands using RF
			showDurabilityBarForRF = true
			#Set the type of durability consumption for all wands
			#Allowed Values: NONE, DURABILITY, XP, EASY_RF, NORMAL_RF, HARD_RF
			wandUsage = "NORMAL_RF"

		[general.wandsettings.teleportation_wand]
			#Volume of the teleportation sound (set to 0 to disable)
			# Default: 1.0
			# Range: 0.0 ~ 10.0
			teleportVolume = 1.0
			#Maximum teleportation distance
			# Default: 30
			# Range: 1 ~ 1000000
			maxTeleportationDist = 30
			#If set to true then sneak-right click will teleport through walls. Otherwise sneak-right click will teleport half distance
			teleportThroughWalls = true

		[general.wandsettings.acceleration_wand]
			#If true this wand will be less effective for fake players
			lessEffectiveForFakePlayer = false
			#Factor to apply to the cost when this wand is used by a fake player (a machine). Set to -1 to disable its use this way
			# Default: 1.0
			# Range: -1.0 ~ 1.0E8
			fakePlayerFactor = 1.0

		[general.wandsettings.capturing_wand]
			#Allow capturing passive mobs
			allowPassive = true
			#Allow capturing hostile mobs
			allowHostile = true
			#Multiply the HP of a mob with this number to get the difficulty scale that affects XP/RF usage (a final result of 1.0 means that the default XP/RF is used)
			# Default: 0.0
			# Range: 0.0 ~ 1.0E8
			difficultyMult = 0.0
			#Add this to the HP * difficultyMult to get the final difficulty scale that affects XP/RF usage (a final result of 1.0 means that the default XP/RF is used)
			# Default: 1.0
			# Range: 0.0 ~ 1.0E8
			difficultyAdd = 1.0
			#Additional cost factor for capturing entities. -1 to prevent capturing
			entityBlackList = []

		[general.wandsettings.freezing_wand]
			#Allow freezing passive mobs
			freezeAllowPassive = true
			#Allow freezing hostile mobs
			freezeAllowHostile = true
			#Multiply the HP of a mob with this number to get the difficulty scale that affects XP/RF usage (a final result of 1.0 means that the default XP/RF is used)
			# Default: 0.0
			# Range: 0.0 ~ 1.0E8
			freezeDifficultyMult = 0.0
			#Add this to the HP * difficultyMult to get the final difficulty scale that affects XP/RF usage (a final result of 1.0 means that the default XP/RF is used)
			# Default: 1.0
			# Range: 0.0 ~ 1.0E8
			freezeDifficultyAdd = 1.0

		[general.wandsettings.potion_wand]
			#Allow the potion wand to affect passive mobs
			potionAllowPassive = true
			#Allow the potion wand to affect hostile mobs
			potionAllowHostile = true
			#Multiply the HP of a mob with this number to get the difficulty scale that affects XP/RF usage (a final result of 1.0 means that the default XP/RF is used)
			# Default: 0.0
			# Range: 0.0 ~ 1.0E8
			potionDifficultyMult = 0.0
			#Add this to the HP * difficultyMult to get the final difficulty scale that affects XP/RF usage (a final result of 1.0 means that the default XP/RF is used)
			# Default: 1.0
			# Range: 0.0 ~ 1.0E8
			potionDifficultyAdd = 1.0

	#Settings for the wands
	[general.protectionwand]
		#If this is >= 1 then the protection data will be synced to the client with this frequency (in ticks). This makes protection cleaner at the cost of network traffic
		# Default: -1
		# Range: > 0
		clientSideProtection = 0
		#If this is true then the protection wand will prevent ALL kind of interaction with protected blocks. If this is false then only block breaking is prevented
		interactionProtection = false
		#How far around the player protected blocks will be hilighted
		# Default: 10
		# Range: 1 ~ 50
		blockShowRadius = 10
		#The maximum number of blocks to protect with this wand (set to 0 for no maximum)
		# Default: 16
		# Range: 1 ~ 10000
		maximumProtectedBlocks = 16

	#Settings for the wands
	[general.buildingwands]
		#Set the maximum hardness that the displacement and moving wands can move
		# Default: 50.0
		# Range: 0.0 ~ 1.0E9
		maxHardness = 50.0
		#How far away the hardness can be to allow swapping (100 means basically everything allowed)
		# Default: 35.0
		# Range: 0.0 ~ 100.0
		hardnessDistance = 35.0
		#Distance at which to place blocks in 'in-air' mode
		# Default: 4
		# Range: > 0
		maxPlaceDistance = 4
		#Additional cost factor for moving/swapping blocks. -1 to prevent moving/swapping
		blockBlackList = ["rftoolsbuilder:shielding_solid,-1", "rftoolsbuilder:shielding_translucent,-1", "rftoolsbuilder:shielding_cutout,-1", "rftoolsbuilder:shielding,-1", "minecraft:spawner,5", "minecraft:bedrock,-1", "minecraft:nether_portal,-1", "minecraft:end_portal_frame,-1", "minecraft:end_portal,-1"]
