[features]
	#Defines the cinematic camera while zooming.
	#'OFF' disables the cinematic camera
	#'VANILLA' uses Vanilla's cinematic camera.
	#'MULTIPLIED' is a multiplied variant of 'VANILLA'
	#Allowed Values: OFF, VANILLA, MULTIPLIED
	cinematic_camera = "OFF"
	#Reduces the mouse sensitivity when zooming.
	reduce_sensitivity = true
	#Adds transitions between zooms.
	#'OFF' disables transitions.
	#'SMOOTH' replicates Vanilla's dynamic FOV.
	#'LINEAR' removes the smoothiness.
	#Allowed Values: OFF, SMOOTH, LINEAR
	zoom_transition = "SMOOTH"
	#The behavior of the zoom key.
	#'HOLD' needs the zoom key to be hold.
	#'TOGGLE' has the zoom key toggle the zoom.
	#'PERSISTENT' makes the zoom permanent.
	#Allowed Values: HOLD, TOGGLE, PERSISTENT
	zoom_mode = "HOLD"
	#Allows to increase or decrease zoom by scrolling.
	zoom_scrolling = true
	#Adds zoom manipulation keys along with the zoom key.
	#Note that this config will NOT prevent the keybinds from being registered, but they will become unusable if false.
	extra_key_binds = true
	#Adds an overlay in the screen during zoom.
	#'VIGNETTE' uses a vignette as the overlay.
	#'SPYGLASS' uses the spyglass overlay with the vignette texture.
	#The vignette texture can be found at: assets/okzoomer/textures/misc/zoom_overlay.png
	#Allowed Values: OFF, VIGNETTE, SPYGLASS
	zoom_overlay = "OFF"
	#Determines how the zoom will depend on the spyglass.
	#'REQUIRE_ITEM' will make zooming require a spyglass.
	#'REPLACE_ZOOM' will replace spyglass's zoom with Ok Zoomer's zoom.
	#'BOTH' will apply both options at the same time.
	#The 'REQUIRE_ITEM' option is configurable through the okzoomer:zoom_dependencies item tag.
	#Allowed Values: OFF, REQUIRE_ITEM, REPLACE_ZOOM, BOTH
	spyglass_dependency = "OFF"
	#If the OkZoomer overlay should be disabled when the HUD is hidden. (F1 mode)
	disable_overlay_no_hud = true

[values]
	#The divisor applied to the FOV when zooming.
	#Range: 0.0 ~ 1.7976931348623157E308
	zoom_divisor = 4.0
	#The minimum value that you can scroll down.
	#Range: 0.0 ~ 1.7976931348623157E308
	minimum_zoom_divisor = 1.0
	#The maximum value that you can scroll down.
	#Range: 0.0 ~ 1.7976931348623157E308
	maximum_zoom_divisor = 50.0
	#The number of steps between the zoom divisor and the maximum zoom divisor.
	#Used by zoom scrolling.
	#Range: > 0
	upper_scroll_steps = 20
	#The number of steps between the zoom divisor and the minimum zoom divisor.
	#Used by zoom scrolling.
	#Range: > 0
	lower_scroll_steps = 4
	#The multiplier used for smooth transitions.
	#Range: -1.0 ~ 1.0
	smooth_multiplier = 0.75
	#The multiplier used for the multiplied cinematic camera.
	#Range: -4.0 ~ 4.0
	cinematic_multiplier = 4.0
	#The minimum value that the linear transition step can reach.
	#Range: 0.0 ~ 1.7976931348623157E308
	minimum_linear_step = 0.125
	#The maximum value that the linear transition step can reach.
	#Range: 0.0 ~ 1.7976931348623157E308
	maximum_linear_step = 0.25

[tweaks]
	#Allows resetting the zoom with the middle mouse button.
	reset_zoom_with_mouse = true
	#If enabled, the spyglass overlay texture is used instead of Ok Zoomer's overlay texture.
	use_spyglass_texture = false
	#If enabled, the zoom will use spyglass sounds on zooming in and out.
	use_spyglass_sounds = false
	#Shows toasts when the server imposes a restriction.
	show_restriction_toasts = true
