#Max Stored Time Possible in ticks
max_stored_time = 622080000
#Ticks constant in ticks
ticks_const = 20
#Each use Duration in seconds
each_use_duration = 30
#Define maximum time the items can be used continuously. Corresponding to maximum times faster: Eg. 2^8=256
max_rate_multi = 8
