#Allow bone meal to work on fully grown stems to force producing a melon or pumpkin block.
allow_fruit_stems = true
#Allow bone meal to work on lily pads making them spread around on water.
allow_lily_pad = true
#Allow bone meal to work on nether warts.
allow_nether_wart = true
#Allow bone meal to work on podzol for creating ferns and sweet berry bushes.
allow_podzol = true
#Allow bone meal to work on vines.
allow_vines = true
#Allow bone meal to work on chorus plants and flowers.
#The algorithm searches upwards for connected chorus flowers and has a range limit of 48 blocks.
allow_chorus = true
#Allow bone meal to work on small flowers making them spread around.
allow_small_flowers = true
#Allow bone meal to work on coral turning it into coral reef tree structures for farming coral blocks.
#This does only work when inside of a warm ocean biome and requires a fair bit of open space above the coral.
allow_corals = true
#Allow bone meal to work on sugar canes.
allow_sugar_cane = true
#Allow bone meal to work on mycelium blocks, spawning various types of mushrooms in the vicinity.
allow_mycelium = true
#Allow bone meal to work on all kinds of dirt blocks for converting into a grass block or mycelium when such a block is right next to it.
allow_dirt = true
#Allow bone meal to work on cactus.
allow_cactus = true
#Allow bone meal to work on dead bushes making them spread around.
allow_dead_bush = true

