#Rotate crafting table contents so they always face the closest player.
#Allowed Values: CLOSEST_PLAYER, CRAFTING_PLAYER, NEVER
rotate_ingredients = "CLOSEST_PLAYER"
#Makes crafting table contents lay flat on the table instead of floating above.
flat_rendering = false
#Render the result of the crafting operation in addition to crafting table contents.
render_result = true
