	#Configurations to override server config
	[waterframes.overrideConfig]
		#Enables the option
		enable = false
		#Overrides 'waterframes.watermedia.enable' option
		#Enables VLC/FFMPEG usage for multimedia processing (support added by WATERMeDIA)
		useMultimedia = false
		#overrides 'waterframes.rendering.keepRendering'
		#Enables media processing and rendering, disabling it will not render nothing, you can still hear videos
		keepRendering = false
		#WARNING: DO NOT CHANGE IT EXCEPT IF YOU KNOW WHAT ARE YOU DOING, TOGGLING IT ON MAY CAUSE CORRUPTIONS, UNEXPECTED BEHAVIORS OR WORLD DESTRUCTION
		#forces WATERMeDIA and WATERFrAMES to run in developer mode
		#This is was done for developers who has mods that causes compatibilities with waterframes (or watermedia)
		#Let those modders test waterframes x incompatible mods (i see you stellarity owner)
		forceDevMode = false
